# Generated by Django 4.2.21 on 2025-05-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeanalysis',
            old_name='resume_text',
            new_name='original_resume',
        ),
        migrations.RenameField(
            model_name='resumeanalysis',
            old_name='predicted_jobs',
            new_name='predictions',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='suggestion',
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
